name: Tests
on: push
jobs:
  Tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run tests
      run: yarn test

    - uses: actions/checkout@master

    - uses: codecov/codecov-action@v2
